modLoader="javafml"
license="MIT License"
loaderVersion="[35,)"
issueTrackerURL=""
logoFile="logo.png"

[[mods]]
modId="mimi"
displayName="MIMI"
version="${file.jarVersion}"
authors="tofodroid"
description='''
MIMI - Musical Instrument Minecraft Interface
'''

[[dependencies.mimi]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.0,)"
[[dependencies.mimi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    side="BOTH"
[[dependencies.mimi]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16,1.17)"
    side="BOTH"